services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - "8088:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - app-net

  franken:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.franken
    ports:
      - "8080:80"
      - "2019:2019"
    volumes:
      - .:/var/www/html
      - ./docker/Caddyfile.regular:/etc/frankenphp/Caddyfile
    tty: true
    env_file:
      - .env
    environment:
      SERVER_NAME: ":80"
    networks:
      - app-net

  franken-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.franken
    ports:
      - "8081:80"
      - "2020:2019"
    volumes:
      - .:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/Caddyfile:/etc/frankenphp/Caddyfile
    tty: true
    env_file:
      - .env
    environment:
      APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"
      SERVER_NAME: ":80"
    networks:
      - app-net

  opcache-dashboard:
    build:
      context: ./opcache
      dockerfile: ./Dockerfile
      args:
        VERSION: 0.6.0
    ports:
      - "42042:42042"
    volumes:
      - ./opcache/config.yaml:/config.yaml:ro
    command:
      - --config=/config.yaml
    networks:
      - app-net

  php-fpm-exporter:
    image: hipages/php-fpm_exporter:latest
    depends_on:
      - app
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://app:9000/fpm-status"
    ports:
      - "9253:9253"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: symfony
      GF_SECURITY_ADMIN_PASSWORD: symfony
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-net

volumes:
  caddy_data:
  caddy_config:

networks:
  app-net:
    driver: bridge

