pullInterval: 5

clusters:
  app:
    groups:
      app:
        urlPattern: "http://{host}:80/agent-pull.php"
        hosts:
          - "app"
      franken:
        urlPattern: "http://{host}:80/agent-pull.php"
        hosts:
          - "franken"
          - "franken-worker"
ui:
  host: 0.0.0.0
  port: 42042

metrics:
  statsd:
    enabled: true
    host: "127.0.0.1"
    port: 8125
    prefix: "opcache.stats"
  prometheus:
    enabled: true
    prefix: "opcache_stats"